# docker image to build custom n8n task runner
# https://docs.n8n.io/deploy/host-n8n/configure-n8n/set-up-task-runners#adding-extra-dependencies

FROM n8nio/runners:local

USER root

# fix missing src issue; install task-runner-python module
RUN cd /opt/runners/task-runner-python && \
    uv pip install --python .venv/bin/python .

# TODO move to install-requires/lockfiles
RUN cd /opt/runners/task-runner-python && uv pip install pypdfium2 pillow
USER runner
